Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('blog_content/', views.blogcontent, name='bcontent'),
    path('blog_detail/<str:id>/<slug:slug>', views.blogdetail, name='bdetail'),
    # path('comment/<str:id>', views.comment, name='comment')
]

home/urls.py
from django.urls import path 
from . import views 



urlpatterns = [
    path('', views.index, name='index'),
    path('updateme', views.updateme, name='updateme'),
    path('average/<str:id>', views.average, name='average'),
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'

urlpatterns = [
    path('', views.index, name='order'),
    path('addtocart/', views.addtocart, name='addtocart'),
    path('shopcart/', views.cart, name='cart' ),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name = 'placeorder'),
    path('ordercompleted/', views.ordercompleted, name='ordercompleted'),
    # path('updatequantity/', views.updatequantity, name= 'updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
]

home/models.py
from django.db import models
from django.forms import ModelForm
from ckeditor_uploader.fields import RichTextUploadingField

class Setting(models.Model):
    STATUS =(
        ('True', 'True'),
        ('False', 'False'),
    )

    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)
    company = models.CharField(max_length=50, null=True)
    address = models.CharField( max_length=100)
    phone = models.CharField( null=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    icon = models.ImageField(blank=True,null=True,  upload_to='images/')
    logo = models.ImageField(blank=True,null=True, upload_to='images/')
    default_pic = models.ImageField(blank=True,null=True, upload_to='images/')
    menu_icon = models.ImageField(blank=True,null=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    about =RichTextUploadingField(blank=True)
    contact =RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)

    
    def __str__(self):
        return self.title


class Banner_one(models.Model):
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    banner_text = models.CharField(max_length=20)

    def __str__(self):
        return self.banner_text
    

    class Meta:
        db_table = 'banner_one'
        managed = True 
        verbose_name = 'banner_one'
        verbose_name_plural = 'banner_one'
        



class Banner_two(models.Model):
    image1 = models.ImageField(null=True, blank=True, upload_to='images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='images/')
    image3 = models.ImageField(null=True, blank=True, upload_to='images/')
    banner_text = models.CharField(max_length=20)

    def __str__(self):
        return self.banner_text

    class Meta:
        db_table = 'banner_two'
        managed = True 
        verbose_name = 'banner_two'
        verbose_name_plural = 'banner_two'

class Banner_three(models.Model):
    image1 = models.ImageField(null=True, blank=True, upload_to='images/')
    image2 = models.ImageField(null=True, blank=True, upload_to='images/')
    image3 = models.ImageField(null=True, blank=True, upload_to='images/')
    banner_text = models.CharField(max_length=20)

    def __str__(self):
        return self.banner_text

    class Meta:
        db_table = 'banner_three'
        managed = True 
        verbose_name = 'banner_three'
        verbose_name_plural = 'banner_three'


class UpdateMe(models.Model):

    email = models.CharField(blank=True, max_length=50)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.email


class UpdateMeForm(ModelForm):
    class Meta:
        model= UpdateMe
        fields = [ 'email',]
    

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . models import *
from products.models import *
from django.contrib import messages

# Create your views here.

def index(request):

    setting = Setting.objects.get(pk=1)
    banner1 = Banner_one.objects.all()
    banner2 = Banner_two.objects.get(pk=1)
    banner3 = Banner_three.objects.get(pk=1)
    brands = Brand.objects.all()
    categories = Category.objects.all()
    featured = Product.objects.filter(featured=True)
    reco = Product.objects.filter(recommended=True)
    cat = Category.objects.all()

    context = {
        'setting': setting,
        'banner': banner1,
        'banner2': banner2,
        'banner3': banner3,
        'brands': brands,
        'cat': categories,
        'featured': featured,
        'reco': reco,
        'cat': cat,
    }
    return render(request, 'home.html', context)

def average(request, id):

    reviews = Review.objects.filter(product__id=id)
    avg = reviews.aggregate(Avg("rate"))
    print(avg, '...................')

    context = {
        'avg':avg,
    }

    return render( request, 'home_content.html', context)


def updateme(request):
    if request.method == 'POST':
        form = UpdateMeForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your message has been sent!")
            return redirect('/')

    return render(request, 'home.html', context)

home/templates/banner.html
<!-- banner -->
<div class="banner">
    <div class="bannerC owl-carousel owl-theme" style="max-width: 95%;">
    
        
        {% if banner %}
            {% for item in banner %}
                <div class="item" style="height: 17rem; float:right; display:flex">
                    <div class="text" style=" color:white;">
                        <h1 style="font-size:5rem;margin-top: 160px; background:rgb(128, 128, 128, 0.5);padding-inline:20px ">{{item.banner_text}}</h1>
                    </div>
                    <img style="width: 25rem;" src="{{item.image.url}}" alt="">
                </div>
            {% endfor %}
        {% endif %}
            
    
    </div>
</div>

home/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '' %}css/main.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- <meta name="viewport" content="{% block keywords %} Home {% endblock keywords %}"> -->
    <title>{% block title %} {{setting.title}}{% endblock title %}</title>
</head>
<body>
    <div class="main_body home">

        {% block header %}
          
        {% endblock header %}

        {% block banner %}
        
        {% endblock banner %}
        

        {% block content %}

        {% endblock content %}

        

        {% block footer %}

        {% endblock footer %}
        
        <div class="back_to_top">
            <a href="#top"><i class="fa fa-angle-up" aria-hidden="true"></i></a>
        </div>
    </div>
    
    
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js" integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script type="text/javascript">
        $(".bannerC").owlCarousel({
            loop:true,
            margin:20,
            nav:false,
            autoplay:true,
            autoplayTimeout: 5000,
            dots:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:1
                },
                1000:{
                    items:1
                }
            }
        });


        $(".reco").owlCarousel({
            loop:true,
            margin:20,
            nav:true,
            autoplay:false,
            autoplayTimeout: 1000,
            stagePadding: 90,
            dots:true,
            responsive:{
                0:{
                    items:1
                },
                600:{
                    items:2
                },
                1000:{
                    items:5
                }
            }
        });
    </script>
</body>
</html>

home/templates/footer.html
{% load static %}
<section class="footer">
    <div class="row foot container-fluid">
        <div class="col-lg-2 log_text">
            <img src="images/home/logo.png" alt="">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor
            </p>
        </div>
        
        <div class="video col-lg-2">
            <video width="140" controls>
                <source src="{% static '' %}videos/videoplayback (4).mp4" type="video/mp4">
                your browser does not support the video tag
            </video>
        </div>
        <div class="video col-lg-2">
            <video width="140" controls>
                <source src="{% static '' %}videos/videoplayback (4).mp4" type="video/mp4">
                your browser does not support the video tag
            </video>
        </div>
        <div class="video col-lg-2">
            <video width="140" controls>
                <source src="{% static '' %}videos/videoplayback (4).mp4" type="video/mp4">
                your browser does not support the video tag
            </video>
        </div>

        <div class="video col-lg-2">
            <video width="140" controls>
                <source src="{% static '' %}videos/videoplayback (4).mp4" type="video/mp4">
                your browser does not support the video tag
            </video>
        </div>
        
        <div class=" loc col-lg-2">
            <img src="images/home/map.png" alt="" style="width: 14rem;">
            <div class="location" >
                <p>{{setting.address}}</p>
            </div>
        </div>
    </div>
    
    <div class="footer_info fluid-container">
        
        <div class="row">
            <div class="col-2 col-sm-2 col-lg-2">
                <h5>User</h5>
                <div>
                    <li><a href="#">Home</a></li>
                    <li><a href="">Profile Update</a></li>
                    <li><a href="">Change Password</a></li>
                    <li><a href="">ShopCart</a></li>
                    <li><a href="">Logout</a></li>
                </div>
            </div>
            <div class="cl-2 col-sm-2 col-lg-2">
                <h5>Quick Shop</h5>
                <div>
                    <li><a href="">T-shirt</a></li>
                    <li><a href="">Men</a></li>
                    <li><a href="">Women</a></li>
                    <li><a href="">Gift cards</a></li>
                    <li><a href="">Shoes</a></li>
                </div>
            </div>
            <div class="col-2 col-sm-2 col-lg-2">
                <h5>Policies</h5>
                <div>
                    <li><a href="">Terms Of Use</a></li>
                    <li><a href="">Privacy Policy</a></li>
                    <li><a href="">Refund Policy</a></li>
                    <li><a href="">Billing Policy</a></li>
                    <li><a href="">Ticket Policy</a></li>
                </div>
            </div>
            <div class=" col-2 col-sm-2 col-lg-2">
                <h5>About Store</h5>
                <div>
                    <li><a href="">Company Information</a></li>
                    <li><a href="">Our Engineers</a></li>
                    <li><a href="">Store Location</a></li>
                    <li><a href="">Contact us</a></li>
                    <li><a href="">Copyright</a></li>
                </div>
            </div>
            <div class="col-2 col-sm-2 upda">
                <h5>Recieve Updates</h5>
                <div class=" update" >
                    <form action="{% url 'updateme' %}" method="POST">
                    {% csrf_token %}
                        <input type="email" class="form-control" placeholder="Email Address"  style="border: 1px solid black;" name="email">
                        <button type="submit" >send <i class="fa fa-paper-plane"></i></button>
                    </form>
                </div>
                <p>Get the most recent updates from <br>
                    our site and be updated your self...</p>
            </div>
            
        </div>
    </div>
    <div class="">
        <div class="copyright">
            <p>copyright &copy; 2021 Shopper inc. All right reserved.</p>
            <p> Designed by  Oluwatomisin</p>
        </div>
    </div>
</section>

home/templates/header.html
<header class="main_header" id="top">
    <div class="header_one">
        <div class="container container--flex">
            <div class="contact">
                <p> +2 95 01 88 821</p>
                <p>info@domain.com</p>    
            </div>
            <ul class="social_media_handles">
                <div><i class="fa fa-facebook" aria-hidden="true"></i></div>
                <div><i class="fa fa-twitter" aria-hidden="true"></i></div>
                <div><i class="fa fa-dribbble" aria-hidden="true"></i></div>
                <div><i class="fa fa-google-plus" aria-hidden="true"></i></div>
                <div><i class="fa fa-linkedin" aria-hidden="true"></i></div>
            </ul>
        </div>
    </div>
    <div class="header_two">
        <div class="container">
            <div class="row">
                <div class="header_two--logo col col-sm-4 col-md-3 col-lg-3"><img src="{{setting.logo.url}}" alt=""></div>
                <!-- <div class="header_two--dropdown col-sm-4 col-md-3 col-lg-3">
                    <div class="drop">
                        <select name="" id="">
                            <option value=""><p id="currency">USA</p></option>
                            <option value="">Canada</option>
                            <option value="">UK</option>
                        </select>
                    </div>
                    <div class="drop">
                        <select name="" id="">
                            <option value=""><p>Dollar</p></option>
                            <option value="">Canadian Dollar</option>
                            <option value="">Pound</option>
                        </select>
                    </div>
                </div> -->
                
                <div class="header_two--nav-links col-sm-12 col-md-9 col-lg-9 ">
                    <img src="images/menu.png" alt="" class="menu-icon" onclick="menutoggle()">
                    <ul id="MenuItems" class="nav justify-content-end" >
                        
                        
                        
                        
                        {% if user.id is not None %}
                            <li class="">
                                <a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-user" aria-hidden="true"></i>Logout</a>
                            </li>
                            <li class="">
                                <a class="nav-link" href="#"><i class="fa fa-star" aria-hidden="true"></i>Wishlist</a>
                            </li>
                            <li class="">
                                <a class="nav-link" href="{% url 'order:cart' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i>Cart</a>
                            </li>
                            <li class="">
                                <a class="nav-link" href="#"><i class="fa fa-user" aria-hidden="true"></i>Account</a>
                            </li>
                            
                            
                            
                            {% else %}
                            <li class="">
                                <a class="nav-link" href="{% url 'signupform' %}"><i class="fa fa-crosshairs" aria-hidden="true"></i>Sign Up</a>
                            </li>
                            <li class="">
                                <a class="nav-link" href="{% url 'signupform' %}"><i class="fa fa-user" aria-hidden="true"></i>Login</a>
                            </li>
                        
                        {% endif %} 
                            
                    </ul>
                </div>
            </div>
            <hr>
        </div>
    </div>
    <div class="header_three">
       <div class="container">
           <div class="row">
                <ul class="nav col-sm-12 col-md-8 col-lg-8">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" id="shop">Categories <i class="fa fa-angle-down" aria-hidden="true"></i></a>

                        <ul class=" dropdown-menu">
                            {% if cat %}
                                {% for item in cat %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'category' item.id %}">{{item.cat}}</a>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Brands <i class="fa fa-angle-down" aria-hidden="true"></i></a>

                        <ul class="nav dropdown-menu">
                            {% if brands %}
                                {% for item in brands %}
                                    <li class="nav-item">
                                        <a class="nav-link" href="{% url 'brands' item.id %}">{{item.brand}}</a>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'products' %}">Products</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'bcontent' %}">Blog</a>
                    </li>
                </ul>
                <div class="header_three--search col-sm-12 col-md-3 col-lg-3">
                    
                    {% if user.is_authenticated %}
                        <li style="list-style: none; font-size:15px;text-align:right;">
                            <a href="{% url 'userprofile' %}" style="text-decoration: none;"> 
                                        {% if request.user.first_name %}
                                            <p style="font-size: 20px;"><strong>{{request.user.first_name}}</strong></p>
                                        {% else %}
                                            <p><strong>{{request.user.username}}</strong></p>
                                        {% endif %}
                                        
                                    </a>
                        </li>
                    {% endif %}
                        
                </div>
           </div>
       </div>
    </div>
</header>

home/templates/header2.html
<header class="main_header" id="top">
    <div class="header_one">
        <div class="container container--flex">
            <div class="contact">
                <p> +2 95 01 88 821</p>
                <p>info@domain.com</p>    
            </div>
            <ul class="social_media_handles">
                <div><i class="fa fa-facebook" aria-hidden="true"></i></div>
                <div><i class="fa fa-twitter" aria-hidden="true"></i></div>
                <div><i class="fa fa-dribbble" aria-hidden="true"></i></div>
                <div><i class="fa fa-google-plus" aria-hidden="true"></i></div>
                <div><i class="fa fa-linkedin" aria-hidden="true"></i></div>
            </ul>
        </div>
    </div>
    <div class="header_two">
        <div class="container">
            <div class="row">
                <div class="header_two--logo col col-sm-4 col-md-3 col-lg-3"><img src="{{setting.logo.url}}" alt=""></div>
                
                <div class="header_two--nav-links col-sm-12 col-md-6 col-lg-6 ">
                    <img src="images/menu.png" alt="" class="menu-icon" onclick="menutoggle()">
                    <ul id="MenuItems" class="nav justify-content-end" >
                            
                    </ul>
                </div>
            </div>
            <hr>
        </div>
    </div>
    
    <div class="header_three">
       <div class="container">
           <div class="row">
                <ul class="nav col-sm-12 col-md-10 col-lg-10">
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'index' %}" style="font-weight: bold; font-size:18px;">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'profileupdate' %}" id="shop" style="font-weight: bold; font-size:18px;">Update Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile' %}" style="font-weight: bold; font-size:18px;">Profile</i></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="font-weight: bold; font-size:18px;">Change Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#" style="font-weight: bold; font-size:18px;">Order History</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}" style="font-weight: bold; font-size:18px;">Logout</a>
                    </li>
                    <li style="float: right;"><img src="{{profile.image.url}}" alt="" style="height: 40px; width:30px; border-radius: 50%;"></li>
                    {% if user.id is not None %}
                            
                        <li>
                            
                            <a href="{% url 'userprofile' %}"> Hi!
                                
                                {% if request.user.first_name %}
                                    <p style="font-size: normal;"><strong>{{request.user.first_name}}</strong></p>
                                {% else %}
                                    <p><strong>{{request.user.username}}</strong></p>
                                {% endif %}
                                        
                            </a>
                        </li>
                                
                    {% endif %} 
                </ul>
           </div>
           
       </div>
    </div>
</header>

home/templates/home.html
{% extends "base.html" %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}


{% block banner %}
    {% include "banner.html" %}
{% endblock banner %}


{% block content %}
    {% include "home_content.html" %}
{% endblock content %}


{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}