Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('blog_content/', views.blogcontent, name='bcontent'),
    path('blog_detail/<str:id>/<slug:slug>', views.blogdetail, name='bdetail'),
    # path('comment/<str:id>', views.comment, name='comment')
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'

urlpatterns = [
    path('', views.index, name='order'),
    path('addtocart/', views.addtocart, name='addtocart'),
    path('shopcart/', views.cart, name='cart' ),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name = 'placeorder'),
    path('ordercompleted/', views.ordercompleted, name='ordercompleted'),
    # path('updatequantity/', views.updatequantity, name= 'updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
]

order/models.py
from django.db import models

from django.contrib.auth.models import User

from django.forms import ModelForm
from products.models import Product
from django.forms import Select

class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True )
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True )
    quantity = models.IntegerField(blank=True, null=False)
    order_code = models.CharField(max_length=70, editable=False)
    order_placed = models.BooleanField(default=False)


    def __str__(self):
        return self.product.prod_name
    

    @property
    def price(self):
        if self.product_id is not None:
            return (self.product.price)

 
    @property
    def amount(self):
        if self.product_id is None:
            return (None)
        else:
            if self.product.price:
                return(self.product.price * self.quantity)

class ShopCartForm(ModelForm):
    class Meta:
        models = ShopCart
        fields = ['quantity', 'size']




class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('Onshipping', 'Onshippong'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )


    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    prodname = models.CharField(max_length=225, null=True)
    total = models.FloatField(null=True, blank=True)
    order_placed = models.BooleanField(default=False)
    # order_code = models.CharField(max_length=70, editable=False)
    payment_code = models.CharField(max_length=8, editable=False)
    first_name = models.CharField(max_length=15)
    last_name = models.CharField(max_length=15)
    email = models.CharField(max_length=30, null=True)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(max_length=150, blank=True)
    city = models.CharField( blank=True, max_length=20)
    state = models.CharField(blank=True, null=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    status = models.CharField(max_length=10, choices=STATUS, default='new')
    adminnoted = models.CharField(blank=True, max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)




    def __str__(self):
        return self.user.username
    

class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = [ 'first_name', 'last_name', 'address', 'email', 'phone',  'city', 'country']

order/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from user.models import UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from home.models import Setting
from products.models import *
from .models import *
from django.contrib import messages
import uuid
import random
import string 
import json 
import requests



# Create your views here.
def index(request):

    return HttpResponse('this is order')


@require_POST
@login_required(login_url='login')
def addtocart(request):
    url = request.META.get('HTTP_REFERER')
    thequantity = int(request.POST['quantity'])
    theprodid = request.POST['prodid']
    aprod = Product.objects.get(pk=theprodid)

    #check if 9the user has an existing cart
    cart = ShopCart.objects.filter(order_placed=False).filter(user__username = request.user.username)

    if cart: #an existiing cart is noticed
        prodchecker = ShopCart.objects.filter(product_id = aprod.id, quantity=thequantity, user__username= request.user.username).first()

        if prodchecker: #product exists in cart,  increment it
            prodchecker.quantity += thequantity
            prodchecker.save()
            messages.success(request, "product added to shopcart")
            return redirect(url)

        else: #product is not in the cart, add it
            anitem = ShopCart()
            anitem.product=aprod
            anitem.user=request.user
            anitem.order_code=cart[0].order_code
            anitem.quantity=thequantity
            anitem.order_placed=False
            anitem.save()

    else: #create a new cart, generate order code
        ordercode = str(uuid.uuid4())
        newcart = ShopCart()
        newcart.product = aprod
        newcart.user=request.user
        newcart.order_code=ordercode
        newcart.quantity=thequantity
        newcart.order_placed=False
        newcart.save()
    
    messages.success(request, 'Product addd to Shopcart')
    return redirect(url)



@login_required(login_url='login')
def cart(request):
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username=request.user.username)
    brand = Brand.objects.all()
    cat = Category.objects.all()

    subtotal=0
    shippingfee =0
    vat = 0
    total = 0

    for item in shopcart:
        subtotal +=item.product.price * item.quantity
        

    #shipping rules: 8% fees to all orders above 150. 0 fees to oorders lower
    if subtotal > 150:
        shippingfee = 0.08 * subtotal
    else:
        shippingfee = 0
    
    vat = 0.075 * subtotal

    total = subtotal + shippingfee + vat

    context = {
        'cart': shopcart,
        'subtotal': subtotal,
        'shipping': shippingfee,
        'vat': vat,
        'total': total,
        'brands': brand,
        'cat': cat,
}

    return render(request, 'cart.html', context)



@login_required(login_url='login')
def checkout(request):
    shopcart = ShopCart.objects.filter(order_placed=False).filter(user__username=request.user.username)
    profile = UserProfile.objects.get(user__username = request.user.username)
    setting = Setting.objects.get(pk=1)

    subtotal=0
    shippingfee =0
    vat = 0
    total = 0

    for item in shopcart:
        subtotal +=item.product.price * item.quantity
        

    #shipping rules: 8% fees to all orders above 150. 0 fees to oorders lower
    if subtotal > 150:
        shippingfee = 0.08 * subtotal
    else:
        shippingfee = 0
    
    vat = 0.075 * subtotal

    total = subtotal + shippingfee + vat

    context = {
        'cart': shopcart,
        'subtotal': subtotal,
        'shipping': shippingfee,
        'vat': vat,
        'total': total,
        'profile': profile,
        'setting': setting,
}

    return render(request, 'checkout.html', context)

@login_required(login_url='login')
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, 'Item deleted from ShopCart')
    return redirect('order:cart')


@require_POST
@login_required(login_url='login')
def placeorder(request):
    api_key = 'sk_test_d3a8ed0644189273d85e8ac97f71b0e02507ac68'
    url = 'https://api.paystack.co/transaction/initialize'
    callback_url ='http://127.0.0.1:8000/order/ordercompleted/'
    ordercode = request.POST['order_number']
    autogen_ref = ''.join(random.choices(string.digits + string.ascii_letters, k=8))
    current_user = User.objects.get(username = request.user.username)
    user = UserProfile.objects.get(user_id = current_user.id)
    total = float(request.POST['amount']) * 100

    headers = {'Authorization': f'Bearer {api_key}'}
    data = {'reference': autogen_ref, 'amount': int(total), "currency": "NGN", 'order_number':ordercode, 'email':user.email, 'callback_url':callback_url}

    #making a request to paystack
    try:
        r =requests.post(url, headers=headers, json=data)
    except Exception:
        messages.error(request, 'Network busy, please try again in few minutes. Thank You!')
    else:
        #create an order
        transback = json.loads(r.text)

        rd_url = transback['data']['authorization_url']
        theuser = UserProfile.objects.filter(user=request.user).first()
        order = Order()
        order.user=current_user
        order.first_name=theuser.user.first_name
        order.last_name=theuser.user.last_name
        order.phone=theuser.phone
        order.city=theuser.city
        order.address=theuser.address
        order.state=theuser.state
        order.country=theuser.country
        order.email=theuser.email
        order.order_code=ordercode
        order.payment_code= autogen_ref
        order.total=total 
        order.order_placed= True 
        order.save()
        

        return redirect(rd_url)

    return redirect('order:checkout')


@login_required(login_url='login')
def ordercompleted(request):

    return render(request, 'ordercompleted.html')

order/templates/cart.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}
    ShopCart
{% endblock title %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}

{% block content %}
    <div class="container cart">
        <table class="table">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Amount</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                
                {% if cart %}
                    {% for item in cart %}
                    <tr>
                        <td><img src="{{item.product.image.url}}" alt=""> <p><span>Product Name:</span>{{item.product.prod_name}}</p><p><span>Product Id:</span> {{item.product.product_id}}</p></td>
                        <td>${{item.product.price | floatformat:2 | intcomma}}</td>
                        <td><input type="number" value="{{item.quantity}}"></td>
                        <td>${{item.amount | floatformat:2 | intcomma}}</td>
                        <td><a href="{% url 'order:deletefromcart' item.id %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a></td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <h3>Your cart is empty</h3>
                {% endif %}
                    
            </tbody>
        </table>


        
        <div class="rec">
            <div class="deloc col-lg-5">
                <div class="total">
                    <p>Cart Subtotal: <span id="cat"># {{subtotal | floatformat:2 | intcomma}}</span> </p>
                    <p>Vat: <span id="tax"># {{vat | floatformat:2 | intcomma}}</span> </p>
                    <p>Shipping Cost: <span id="ship">$ {{shipping | floatformat:2 | intcomma}}</span> </p>
                    <p>Total: <span id="tot">#{{total | floatformat:2 | intcomma}}</span> </p>
                </div>
                <a href="{% url 'order:checkout' %}" style="padding-block:10px; font-weight:bold;">Checkout</a>
            </div>
        </div>
    </div>
{% endblock content %}


{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

order/templates/checkout.html
{% extends 'base.html' %}
{% load humanize %}

{% block title %}
    Checkout Page
{% endblock title %}

{% block header %}
    {% include "header2.html" %}
{% endblock header %}

{% block content %}
    <div class="back checkout" >
        <div class="container">
            <div class="checkouts">
                <div class="title_div">
                    <hr><h5>CHECKOUT PAGE</h5><hr>
                </div>
                <div class="chek">
                    <p>Review Your  Shopcart and proceed to order</p>
                </div>
                <div class="container cart">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Item</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Amount</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if cart %}
                                {% for item in cart %}
                                    <tr>
                                        <td><img src="{{item.product.image.url}}" alt=""> <p><span>Product Name:</span>{{item.product.prod_name}}</p><p><span>Product Id:</span> {{item.product.product_id}}</p></td>
                                        <td>${{item.product.price | floatformat:2 | intcomma}}</td>
                                        <td><input type="number" value="{{item.quantity}}" readonly></td>
                                        <td>${{item.amount | floatformat:2 | intcomma}}</td>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                    <div class="deloc col-lg-5">
                        <div class="total">
                            <p>Cart Subtotal: <span id="cat"># {{subtotal | floatformat:2 | intcomma}}</span> </p>
                            <p>Vat: <span id="tax"># {{vat | floatformat:2 | intcomma}}</span> </p>
                            <p>Shipping Cost: <span id="ship">$ {{shipping | floatformat:2 | intcomma}}</span> </p>
                            <p>Total: <span id="tot">#{{total | floatformat:2 | intcomma}}</span> </p>
                        </div>
                    </div>
                </div>
                <div class="billto">
                    <p>Bill To</p>
                    <form action="{% url 'order:placeorder' %}" method="POST">
                    {% csrf_token %}
                        <div class="one">
                            <!-- <input type="text" placeholder="Company Name" value="Company name" name="company_name"> <br> -->
                            <input type="text" placeholder="Email" value="{{profile.email}}"> <br>
                            <!-- <input type="text" placeholder="Title" name="title"> <br> -->
                            <input type="text" placeholder="First Name" value="{{profile.first_name}}"> <br>
                            <!-- <input type="text" placeholder="Middle Name" name="middle_name"> <br> -->
                            <input type="text" placeholder="Last Name" value="{{profile.last_name}}"> <br>
                        </div>
                        <div class="two">
                            <input type="text" placeholder="Address" value="{{profile.address}}"> <br>
                            <!-- <input type="text" placeholder="Zip/ Postal Code"> <br> -->
                            <input type="text" placeholder="Country" value="{{profile.country}}"><br>
                            <input type="text" placeholder="State" value="{{profile.state}}"> <br>
                            <input type="text" placeholder="City" value="{{profile.city}}"> <br>
                            <input type="text" placeholder="Mobile Phone" value="{{profile.phone}}" > <br>
                            <!-- <input type="text" placeholder="Home Phone" name="home_phone"> <br> -->
                            <input type="hidden" name="amount" value="{{total}}" >
                            <input type="hidden" name="order_number" value="{{order_code}}" >
                            <button type="submit">Proceed To Order</button>
                        </div>
                        
        
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

order/templates/ordercompleted.html
{% extends 'base.html' %}

{% block title %}
  
{% endblock title %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}

{% block content %}
    <div style="text-align: center; justify-content:center;">
        <h1 >Thanks for Pratronizing us</h1>
        <p>Did you enjoy our service?</p>
        <div>
            <select name="" id="">
                <option value="Yes">Yes</option>
                <option value="No">No</option>
            </select>
            <button id="yes">Submit</button>
        </div>
    </div>
{% endblock content %}

{% block footer %}
   {% include "footer.html" %}
{% endblock footer %}