Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('user/', include('user.urls')),
    path('order/', include('order.urls')),
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views 

urlpatterns = [
    path('blog_content/', views.blogcontent, name='bcontent'),
    path('blog_detail/<str:id>/<slug:slug>', views.blogdetail, name='bdetail'),
    # path('comment/<str:id>', views.comment, name='comment')
]

order/urls.py
from django.urls import path
from . import views



app_name = 'order'

urlpatterns = [
    path('', views.index, name='order'),
    path('addtocart/', views.addtocart, name='addtocart'),
    path('shopcart/', views.cart, name='cart' ),
    path('checkout/', views.checkout, name='checkout'),
    path('placeorder/', views.placeorder, name = 'placeorder'),
    path('ordercompleted/', views.ordercompleted, name='ordercompleted'),
    # path('updatequantity/', views.updatequantity, name= 'updatequantity'),
    path('deletefromcart/<str:id>', views.deletefromcart, name='deletefromcart'),
]

products/urls.py
from django.urls import path
from .import views 


urlpatterns = [
    path('product_page/', views.products, name='products'),
    path('product_detail/<str:id>', views.prod_detail, name = 'prod_detail'),
    path('category/<str:id>', views.category, name='category'),
    path('brands/<str:id>', views.brands, name='brands'),
    path('review/', views.review_rate, name='review'),
]

products/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms


class Category(models.Model):
    cat = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.cat 
    

    class Meta:
        db_table = 'category'
        managed = True 
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
class Brand(models.Model):
    brand = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.brand 

    class Meta:
        db_table = 'brand'
        managed = True
        verbose_name = 'brand'
        verbose_name_plural = 'brands'



class Product(models.Model):

    AVAILABILITY = (
        ('Instock', 'Instock'),
        ('Out of stock', 'Out of stock')
    )

    cat = models.ForeignKey(Category, on_delete= models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete= models.CASCADE)
    prod_name = models.CharField(max_length=50)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    price = models.SmallIntegerField()
    amount = models.IntegerField(null=True, blank=True)
    product_id = models.CharField(max_length=20, null=True, blank=True)
    availability = models.CharField(max_length=20, choices= AVAILABILITY, default='Instock')
    HDD = models.CharField(max_length=50, null=True, blank=True)
    processor = models.CharField(max_length=200, null=True, blank=True)
    RAM = models.CharField(max_length=40, blank=True, null=True)
    screen_size = models.CharField(max_length=50, null=True, blank=True)
    featured = models.BooleanField(blank=True)
    recommended = models.BooleanField(blank=True)
    condition = models.CharField(max_length=20, default= 'New')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.prod_name 

    class Meta:
        db_table = 'product'
        managed = True
        verbose_name = 'product'
        verbose_name_plural = 'products'


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    comment = models.TextField(max_length=225)
    rate = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)
    
    class Meta:
        db_table = 'review'
        managed = True
        verbose_name = 'review'
        verbose_name_plural = 'reviews'

        



# class Review(models.Model):
#     prod = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
#     rev = RichTextUploadingField(blank=True)
#     date = models.DateField(auto_now_add=True)
#     time = models.TimeField(auto_now_add=True)
#     name = models.CharField(max_length=30)
#     active = models.BooleanField(default=True)

#     def __str__(self):
#         return 'Review by {} on {}'.format(self.name, self.prod)

    
# class ReviewForm(forms.ModelForm):
#     class Meta:
#         model  = Review
#         fields = ('rev', 'name')
    

products/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from home.models import Setting, Banner_one
from .models import *
from django.db.models import Avg

# Create your views here.
def products(request):
    setting = Setting.objects.get(pk=1)
    # cat = Category.objects.all()
    brands = Brand.objects.all()
    product = Product.objects.all()
    cat = Category.objects.all()
    # reviews = Review.objects.filter(product__id=id)
    # avg = reviews.aggregate(Avg("rate"))
    

    context = {
        'setting': setting,
        'brands': brands,
        'products': product,
        'cat': cat,
        # 'avg': avg,
    }
    

    return render(request, 'products.html', context)


def prod_detail(request, id):
    product = Product.objects.get(pk=id)
    banner1 = Banner_one.objects.all()
    prodid = Product.objects.get(id=id)
    brands = Brand.objects.all()
    cat = Category.objects.all()
    reviews = Review.objects.filter(product__id=id)
    avg = reviews.aggregate(Avg("rate"))

    

    context = {
        'banner': banner1,
        'product': product,
        'brands': brands,
        'cat': cat,
        'prodid': prodid,
        'reviews': reviews,
        'avg': avg,
    }

    return render(request, 'prod_detail.html', context)


def category(request, id):
    setting = Setting.objects.get(pk=1)
    catego = Product.objects.filter(cat__id=id)
    cat = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'setting': setting,
        'catego': catego,
        'cat': cat,
        'brands': brands,
    }

    return render(request, 'cat.html', context)

def brands(request, id):
    setting = Setting.objects.get(pk=1)
    brand = Product.objects.filter(brand__id=id)
    cat = Category.objects.all()
    brands = Brand.objects.all()

    context = {
        'setting': setting,
        'brand': brand,
        'cat': cat,
        'brands': brands,
    }

    return render(request, 'brand.html', context)


def review_rate(request):
    if request.method == "GET":
        prod_id = request.GET.get('prodid')
        print(prod_id, '........')
        product = Product.objects.get(id=prod_id)
        user = request.user
        comment = request.GET.get('comment')
        rate = request.GET.get('rating')
        Review(product=product, user=user, comment=comment, rate=rate).save()

        return redirect('prod_detail', id=prod_id, )

products/templates/brand.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}
    Brands
{% endblock title %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}

{% block content %}
{% load humanize %}
<section class="index_content product">
    <div class="container whiteback">
        <div class="row">
            <div class="mainbar col-sm-12 col-md-7 col-lg-12">
                <div class="container featured_item">
                    <div class="title_div">
                        <hr><h5>Product by Brand</h5><hr>
                    </div>
                    <div class="row">
                        
                        
                        {% if brand %}
                            {% for item in brand %}
                                <div class="card prod" style="width: 15.5rem;">
                                    <img src="{{item.image.url}}" class="card-img-top" alt="..." style="height: 10rem; margin-top:45px;">
                                    <div class="card-body center_text">
                                        <h4>#{{item.price | floatformat:2 | intcomma}}</h4>
                                        <p>{{item.prod_name}}</p>
                                        <a href="#" class="btn btn-sm">Add To Cart</a>
                                    </div>
                                    <div class="card card_hover" style="width: 15.5rem;">
                                        <div class="card-body center_text">
                                            <h4>#{{item.price | floatformat:2 | intcomma}}</h4>
                                            <p>{{item.prod_name}}</p>
                                            <a href="#" class="btn btn-sm">Add To Cart</a>
                                        </div>
                                    </div>
                                    <div class="wish">
                                        <a href="{% url 'prod_detail' item.id  %}"><i class="fa fa-plus-square" aria-hidden="true"></i>See Product Detail</a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                            
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

products/templates/cat.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}
    category
{% endblock title %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}

{% block content %}
<section class="index_content product">
    <div class="container whiteback">
        <div class="row">
            <div class="mainbar col-sm-12 col-md-7 col-lg-12">
                <div class="container featured_item">
                    <div class="title_div">
                        <hr><h5>Product By Category</h5><hr>
                    </div>
                    <div class="row">
                        
                        
                        {% if catego %}
                            {% for item in catego %}
                                <div class="card prod" style="width: 15.5rem;">
                                    <img src="{{item.image.url}}" class="card-img-top" alt="..." style="height: 10rem; margin-top:45px;">
                                    <div class="card-body center_text">
                                        <h4>#{{item.price | floatformat:2 | intcomma}}</h4>
                                        <p>{{item.prod_name}}</p>
                                        <a href="#" class="btn btn-sm">Add To Cart</a>
                                    </div>
                                    <div class="card card_hover" style="width: 15.5rem;">
                                        <div class="card-body center_text">
                                            <h4>#{{item.price | floatformat:2 | intcomma}}</h4>
                                            <p>{{item.prod_name}}</p>
                                            <a href="#" class="btn btn-sm">Add To Cart</a>
                                        </div>
                                    </div>
                                    <div class="wish">
                                        <a href="{% url 'prod_detail' item.id %}"><i class="fa fa-plus-square" aria-hidden="true"></i>See Product Detail</a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                            
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}


{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

products/templates/prod_content.html
{% load humanize %}
<section class="index_content product">
    <div class="container whiteback">
        <div class="row">
            <div class="mainbar col-sm-12 col-md-7 col-lg-12">
                <div class="container featured_item">
                    <div class="title_div">
                        <hr><h5>PRODUCT PAGE</h5><hr>
                    </div>
                    <div class="row">
                        <style>
                            .checked{
                                color: goldenrod;
                            }
                        </style>
                        
                        
                        {% if products %}
                            {% for item in products %}
                                <div class="card prod" style="width: 15.5rem;">
                                    <img src="{{item.image.url}}" class="card-img-top" alt="..." style="height: 10rem; margin-top:45px;">
                                    <div class="card-body center_text">
                                        <h4>#{{item.price | floatformat:2 | intcomma}}</h4>
                                        <p>{{item.prod_name}}</p>
                                        <div>
                                            {{avg.rate__agv}}
                                            <i class="fa fa-star {% if avg.rate__avg > 0 %} checked {% endif %} " aria-hidden="true"></i>
                                            <i class="fa fa-star {% if avg.rate__avg > 1 %} checked {% endif %}" aria-hidden="true"></i>
                                            <i class="fa fa-star {% if avg.rate__avg > 2 %} checked {% endif %}" aria-hidden="true"></i>
                                            <i class="fa fa-star {% if avg.rate__avg > 3 %} checked {% endif %}" aria-hidden="true"></i>
                                            <i class="fa fa-star {% if avg.rate__avg > 4 %} checked {% endif %}" aria-hidden="true"></i>
                                        </div>
                                    </div>
                                    <div class="card card_hover" style="width: 15.5rem;">
                                        <div class="card-body center_text">
                                            <h4>#{{item.price | floatformat:2 | intcomma}}</h4>
                                            <p>{{item.prod_name}}</p>
                                            <a href="#" class="btn btn-sm">Add To Cart</a>
                                        </div>
                                    </div>
                                    <div class="wish">
                                        <a href="{% url 'prod_detail' item.id %}"><i class="fa fa-plus-square" aria-hidden="true"></i>See Product Detail</a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                            
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

products/templates/prod_detail.html
{% extends "base.html" %}
{% load humanize %}


{% block title %}
    Product Detail
{% endblock title %}


{% block header %}
    {% include "header.html" %}
{% endblock header %}

{% block banner %}
    {% include "banner.html" %}
{% endblock banner %}

{% block content %}

<style>
    form{
        width: 70%;
        margin: left;
    }
    .rate{
        display: flex;
    }
    .rate li{
        display: inline-block;
        margin-right: 10px;
        font-size: 23px;
        text-shadow: 2px 2px 6px grey;
        
    }
    .rate li:hover{
        color: goldenrod;
    }
    input[type='radio']{
        display: none;
    }

    .rate li.active,.rate li.secondary-active{
        color: goldenrod;
    }
    .checked{
        color: goldenrod;
    }
    .time p{
        font-size: 11px;
        font-weight: bold;
    }
    .user{
        line-height: 5px;
    }
    .aver{
        text-align: center;
        margin-top: 10px;
        margin-right: 10px;
        font-size: 25px;
        text-shadow: 2px 2px 7px grey;
    }
    .ave_main{
        font-size: 12px;
        text-shadow: none;
    }
</style>
    <!-- content -->
    <section class="index_content product_detail">
        <div class="container whiteback">
            <div class="row">
                <div class="mainbar detial col-sm-12 col-md-12 col-lg-12">
                    <div class="pro_detail">
                        <div class="container">
                            <div class="row">
                                <div class="title_div">
                                    <hr><h5>PRODUCT DETAIL</h5><hr>
                                </div>
                                <div class="prod_img col-lg-6" id="img-container" style="display: block;">
                                    <img src="{{product.image.url}}" alt="" style="margin-top: 40px; margin-left:25px;">
                                    
                                    <div class="aver">
                                        
                                        <i class="fa fa-star {% if avg.rate__avg > 0 %} checked {% endif %} " aria-hidden="true"></i>
                                        <i class="fa fa-star {% if avg.rate__avg > 1 %} checked {% endif %}" aria-hidden="true"></i>
                                        <i class="fa fa-star {% if avg.rate__avg > 2 %} checked {% endif %}" aria-hidden="true"></i>
                                        <i class="fa fa-star {% if avg.rate__avg > 3 %} checked {% endif %}" aria-hidden="true"></i>
                                        <i class="fa fa-star {% if avg.rate__avg > 4 %} checked {% endif %}" aria-hidden="true"></i>
                                        <p class="ave_main"><span style="font-weight: bold;">Average Rating</span> {{avg.rate__avg}}</p>
                                    </div>
                                </div>
                                <div class="prod_info col-lg-6">
                                    <h5>{{product.prod_name}}</h5>
                                    <p>Product ID:</p>
                                    
                                    
                                    <div class="price">
                                        <p> <span> ${{product.price | floatformat:2 | intcomma}}</span> </p>
                                        <form action="{% url 'order:addtocart' %}" method="POST">
                                        {% csrf_token %}
                                            <p>Quantity: <input type="number" name="quantity"></p>
                                            <input type="hidden" name="prodid" value="{{product.id}}">
                                            <button type="submit" style="transform: translateX(-6rem);">Add To Cart</button>
                                        </form>
                                    </div>
                                    <p><span>Availability: </span>{{product.availability}}</p>
                                    <p> <span>Condition :</span>  {{product.condition}}</p>
                                    <p> <span>Brand :</span> {{product.brand}}</p>
                                    <p><span>Configuration:</span></p>
                                    <p><span>HDD -</span>  {{product.HDD}}, <span>Processor -</span> {{product.processor}}, <span> Memory - </span> {{product.RAM}},  <span> Screen Size -</span>  {{product.screen_size}}</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <h4 style="margin-top: 50px;">Ratings({{reviews.count}})...</h4>
                    <hr>
                    <div>
                        {% if reviews %}
                            {% for item in reviews %}
                        
                                <div style="display: flex; justify-content:space-between">
                                    <div class="user" style="display: block;">
                                        <div>
                                            <p>{{item.comment}}</p>
                                        </div>
                                        <div class="time" style="display: flex;">
                                            <p><i class="fa fa-user" aria-hidden="true"></i>{{item.user.username}}</p>
                                            <p><i class="fa fa-clock-o" aria-hidden="true"></i>{{item.created_at}}</p>
                                        </div>
                                    </div>
                        
                                    <div class="rating">
                                        <i class="fa fa-star {% if item.rate > 0 %} checked {% endif %} " aria-hidden="true"></i>
                                        <i class="fa fa-star {% if item.rate > 1 %} checked {% endif %}" aria-hidden="true"></i>
                                        <i class="fa fa-star {% if item.rate > 2 %} checked {% endif %}" aria-hidden="true"></i>
                                        <i class="fa fa-star {% if item.rate > 3 %} checked {% endif %}" aria-hidden="true"></i>
                                        <i class="fa fa-star {% if item.rate > 4 %} checked {% endif %}" aria-hidden="true"></i>
                                    </div>
                                </div>
                                <hr>
                        
                            {% endfor %}
                        {% endif %}

                        <hr>
                        <div>
                            <form action="{% url 'review' %}" method="GET">
                            {% csrf_token %}
                                <p>Rate This Product</p>
                                <input type="hidden" name="prodid" value="{{prodid.id}}">
                                <textarea name="comment" id="" cols="50" rows="5" placeholder="Right Your Review"></textarea>
                                <ul class="rate">
                                    <li><label for="star_1"><i class="fa fa-star" aria-hidden="true"></i></label><input type="radio" name="rating" id="star_1" value="1"></li>
                                    <li><label for="star_2"><i class="fa fa-star" aria-hidden="true"></i></label><input type="radio" name="rating" id="star_2" value="2"></li>
                                    <li><label for="star_3"><i class="fa fa-star" aria-hidden="true"></i></label><input type="radio" name="rating" id="star_3" value="3"></li>
                                    <li><label for="star_4"><i class="fa fa-star" aria-hidden="true"></i></label><input type="radio" name="rating" id="star_4" value="4"></li>
                                    <li><label for="star_5"><i class="fa fa-star" aria-hidden="true"></i></label><input type="radio" name="rating" id="star_5" value="5"></li>
                                </ul>
                                
                                {% if user.is_authenticated %}
                                    <button type="submit" style="transform: translateX(19rem) translateY(-3rem); ">Rate</button>
                                {% else %}
                                    <p>You have to be logged in to rate the product. <a href="{% url 'login' %}">login</a> or <a href="{% url 'login' %}">signup</a>  </p>
                                {% endif %}
                                    
                            </form>
                        </div>
                        

                    </div>
                    
                </div>
            </div>
        </div>
    </section>

    <script>
        $("li").on("click", function(){
            $("li").removeClass("active");
            $("li").removeClass("secondary-active");
            $(this).addClass("active");
            $(this).prevAll().addClass("secondary-active");
        })
    </script>
    
    
{% endblock content %}


{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}

products/templates/products.html
{% extends 'base.html' %}

{% block title %}
   products page
{% endblock title %}

{% block header %}
    {% include "header.html" %}
{% endblock header %}


{% block content %}
    {% include "prod_content.html" %}
{% endblock content %}


{% block footer %}
    {% include "footer.html" %}
{% endblock footer %}